export let state = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam ",
  "Bihar ",
  "Chhattisgarh ",
  "Goa ",
  "Gujarat ",
  "Haryana ",
  "Himachal ",
  "Jharkhand ",
  "Karnataka ",
  "Kerala ",
  "Madhya ",
  "Maharashtra ",
  "Manipur ",
  "Meghalaya ",
  "Mizoram ",
  "Nagaland ",
  "Odisha ",
  "Punjab ",
  "Rajasthan ",
  "Sikkim ",
  "Tamil ",
  "Telangana ",
  "Tripura ",
  "Uttar ",
  "Uttarakhand ",
  "West ",
];

export const city = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Ahmedabad",
  "Pune",
  "Surat",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Visakhapatnam",
  "Bhopal",
  "Patna",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Vadodara",
];

export const bloodGroups = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];

export const religions = [
  "Hinduism",
  "Islam",
  "Christianity",
  "Sikhism",
  "Buddhism",
];
